// What each class and subclass gains per level, and the feats. Generated by tools/update_classes.py from bg3.wiki;
// do not edit by hand, re-run the script instead.
// BG3_CLASSES[class] = { levels: {class level: [features]}, subclassLevel, subclasses: {name: {class level: [features]}} }
// BG3_FEATS = [[name, what it does], ...]
window.BG3_CLASSES_DATE = "2026-10-04";
window.BG3_CLASSES = {
 "Barbarian": {
  "levels": {
   "1": [
    "Rage",
    "Unarmoured Defence"
   ],
   "2": [
    "Reckless Attack",
    "Danger Sense"
   ],
   "3": [
    "Choose a subclass"
   ],
   "4": [
    "Feat"
   ],
   "5": [
    "Extra Attack",
    "Fast Movement"
   ],
   "6": [
    "Subclass feature"
   ],
   "7": [
    "Feral Instinct"
   ],
   "8": [
    "Feat"
   ],
   "9": [
    "Brutal Critical"
   ],
   "10": [
    "Subclass feature"
   ],
   "11": [
    "Relentless Rage"
   ],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 3,
  "subclasses": {
   "Berserker": {
    "3": [
     "Rage Becomes Frenzy",
     "Frenzy"
    ],
    "6": [
     "Mindless Rage"
    ],
    "10": [
     "Intimidating Presence"
    ]
   },
   "Giant (barbarian subclass)": {
    "3": [
     "Giant's Rage",
     "Vaprak's Greed",
     "Thaumaturgy"
    ],
    "5": [
     "Boot of the Giants"
    ],
    "6": [
     "Elemental Cleaver"
    ],
    "10": [
     "Mighty Impel"
    ]
   },
   "Wild Magic (barbarian subclass)": {
    "3": [
     "Rage: Wild Magic",
     "Magic Awareness"
    ],
    "6": [
     "Bolstering Magic: Boon"
    ],
    "10": [
     "Unstable Backlash"
    ]
   },
   "Wildheart": {
    "3": [
     "Speak with Animals",
     "Bestial Heart"
    ],
    "6": [
     "Animal Aspect"
    ],
    "8": [
     "Land's Stride: Difficult Terrain",
     "Land's Stride: Advantage",
     "Land's Stride: Plants"
    ]
   }
  }
 },
 "Bard": {
  "levels": {
   "1": [
    "Spellcasting",
    "Bardic Inspiration ( d6)"
   ],
   "2": [
    "Song of Rest",
    "Jack of All Trades"
   ],
   "3": [
    "Choose a subclass",
    "Expertise"
   ],
   "4": [
    "Feat"
   ],
   "5": [
    "Improved Bardic Inspiration (passive feature) ( d8)",
    "Font of Inspiration"
   ],
   "6": [
    "Countercharm",
    "Subclass feature"
   ],
   "7": [],
   "8": [
    "Feat"
   ],
   "9": [],
   "10": [
    "Improved Bardic Inspiration (passive feature) ( d10)",
    "Expertise",
    "Magical Secrets"
   ],
   "11": [],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 3,
  "subclasses": {
   "College of Glamour": {
    "3": [
     "Mantle of Inspiration"
    ],
    "6": [
     "Mantle of Majesty: Command",
     "Mantle of Inspiration"
    ],
    "10": [
     "Mantle of Inspiration"
    ]
   },
   "College of Lore": {
    "3": [
     "Gain Proficiency in 3 Skills.",
     "Cutting Words"
    ],
    "6": [
     "Magical Secrets"
    ]
   },
   "College of Swords": {
    "3": [
     "Gain Medium Armour Proficiency",
     "Gain Scimitars Proficiency",
     "Blade Flourish",
     "Fighting Style"
    ],
    "6": [
     "Extra Attack"
    ]
   },
   "College of Valour": {
    "3": [
     "Medium Armour",
     "Shields",
     "Martial Weapons Prof",
     "Combat Inspiration"
    ],
    "6": [
     "Extra Attack"
    ]
   }
  }
 },
 "Cleric": {
  "levels": {
   "1": [
    "Spellcasting"
   ],
   "2": [
    "Turn Undead"
   ],
   "3": [
    "2 Domain spells"
   ],
   "4": [
    "Feat"
   ],
   "5": [
    "Destroy Undead"
   ],
   "6": [
    "Subclass feature"
   ],
   "7": [
    "2 Domain spells"
   ],
   "8": [
    "Feat"
   ],
   "9": [
    "2 Domain spells"
   ],
   "10": [
    "Divine Intervention"
   ],
   "11": [],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 1,
  "subclasses": {
   "Death Domain": {
    "1": [
     "Gain Martial Weapons Prof Proficiency",
     "Reaper",
     "Domain Spells",
     "Bone Chill",
     "Bursting Sinew",
     "Toll the Dead",
     "False Life",
     "Ray of Sickness"
    ],
    "2": [
     "Touch of Death"
    ],
    "3": [
     "Domain Spells",
     "Blindness",
     "Ray of Enfeeblement"
    ],
    "5": [
     "Domain Spells",
     "Animate Dead",
     "Vampiric Touch"
    ],
    "6": [
     "Inescapable Destruction"
    ],
    "7": [
     "Domain Spells",
     "Blight",
     "Death Ward"
    ],
    "8": [
     "Divine Strike: Necrotic"
    ],
    "9": [
     "Domain Spells",
     "Cloudkill",
     "Contagion"
    ]
   },
   "Knowledge Domain": {
    "1": [
     "Blessings of Knowledge",
     "Domain Spells",
     "Command",
     "Sleep"
    ],
    "2": [
     "Knowledge of the Ages"
    ],
    "3": [
     "Domain Spells",
     "Calm Emotions",
     "Hold Person"
    ],
    "5": [
     "Domain Spells",
     "Slow",
     "Speak with Dead"
    ],
    "6": [
     "Read Thoughts",
     "Speak With Animals (Cleric)"
    ],
    "7": [
     "Domain Spells",
     "Confusion",
     "Otiluke's Resilient Sphere"
    ],
    "8": [
     "Potent Spellcasting"
    ],
    "9": [
     "Domain Spells",
     "Dominate Person",
     "Telekinesis"
    ]
   },
   "Life Domain": {
    "1": [
     "Gain Heavy Armour proficiency",
     "Disciple of Life",
     "Domain Spells",
     "Bless",
     "Cure Wounds"
    ],
    "2": [
     "Preserve Life"
    ],
    "3": [
     "Domain Spells",
     "Aid",
     "Lesser Restoration"
    ],
    "5": [
     "Domain Spells",
     "Revivify",
     "Beacon of Hope"
    ],
    "6": [
     "Blessed Healer"
    ],
    "7": [
     "Domain Spells",
     "Guardian of Faith",
     "Death Ward"
    ],
    "8": [
     "Divine Strike: Radiant"
    ],
    "9": [
     "Domain Spells",
     "Greater Restoration",
     "Mass Cure Wounds"
    ]
   },
   "Light Domain": {
    "1": [
     "Warding Flare",
     "Domain Spells",
     "Light",
     "Burning Hands",
     "Faerie Fire"
    ],
    "2": [
     "Radiance of the Dawn"
    ],
    "3": [
     "Domain Spells",
     "Flaming Sphere",
     "Scorching Ray"
    ],
    "5": [
     "Domain Spells",
     "Daylight",
     "Fireball"
    ],
    "6": [
     "Improved Warding Flare"
    ],
    "7": [
     "Domain Spells",
     "Guardian of Faith",
     "Wall of Fire"
    ],
    "8": [
     "Potent Spellcasting"
    ],
    "9": [
     "Domain Spells",
     "Destructive Wave",
     "Flame Strike"
    ]
   },
   "Nature Domain": {
    "1": [
     "Gain Heavy Armour Proficiency",
     "Acolyte of Nature",
     "Domain Spells",
     "Speak with Animals",
     "Animal Friendship"
    ],
    "2": [
     "Charm Animals and Plants"
    ],
    "3": [
     "Domain Spells",
     "Barkskin",
     "Spike Growth"
    ],
    "5": [
     "Domain Spells",
     "Plant Growth",
     "Sleet Storm"
    ],
    "6": [
     "Dampen Elements"
    ],
    "7": [
     "Domain Spells",
     "Dominate Beast",
     "Grasping Vine"
    ],
    "8": [
     "Divine Strike: Elemental Fury"
    ],
    "9": [
     "Domain Spells",
     "Insect Plague",
     "Wall of Stone"
    ]
   },
   "Tempest Domain": {
    "1": [
     "Gain Heavy Armour Proficiency",
     "Gain Martial Weapons Prof Proficiency",
     "Wrath of the Storm",
     "Domain Spells",
     "Thunderwave",
     "Fog Cloud"
    ],
    "2": [
     "Destructive Wrath"
    ],
    "3": [
     "Domain Spells",
     "Gust of Wind",
     "Shatter"
    ],
    "5": [
     "Domain Spells",
     "Call Lightning",
     "Sleet Storm"
    ],
    "6": [
     "Thunderbolt Strike"
    ],
    "7": [
     "Domain Spells",
     "Freedom of Movement",
     "Ice Storm"
    ],
    "8": [
     "Divine Strike: Thunder"
    ],
    "9": [
     "Domain Spells",
     "Destructive Wave",
     "Insect Plague"
    ]
   },
   "Trickery Domain": {
    "1": [
     "Blessing of the Trickster",
     "Domain Spells",
     "Charm Person",
     "Disguise Self"
    ],
    "2": [
     "Invoke Duplicity"
    ],
    "3": [
     "Domain Spells",
     "Mirror Image",
     "Pass Without Trace"
    ],
    "5": [
     "Domain Spells",
     "Bestow Curse",
     "Fear"
    ],
    "6": [
     "Channel Divinity: Cloak of Shadows"
    ],
    "7": [
     "Domain Spells",
     "Dimension Door",
     "Polymorph"
    ],
    "8": [
     "Divine Strike: Poison"
    ],
    "9": [
     "Domain Spells",
     "Dominate Person",
     "Seeming"
    ]
   },
   "War Domain": {
    "1": [
     "Gain Heavy Armour proficiency",
     "Gain Martial Weapons Prof proficiency",
     "War Priest",
     "Domain Spells",
     "Divine Favour",
     "Shield of Faith"
    ],
    "2": [
     "Guided Strike"
    ],
    "3": [
     "Domain Spells",
     "Magic Weapon",
     "Spiritual Weapon"
    ],
    "5": [
     "Domain Spells",
     "Spirit Guardians",
     "Crusader's Mantle"
    ],
    "6": [
     "War God's Blessing"
    ],
    "7": [
     "Domain Spells",
     "Freedom of Movement",
     "Stoneskin"
    ],
    "8": [
     "Divine Strike: Weapon"
    ],
    "9": [
     "Domain Spells",
     "Flame Strike",
     "Hold Monster"
    ]
   }
  }
 },
 "Druid": {
  "levels": {
   "1": [
    "Spellcasting"
   ],
   "2": [
    "Wild Shape",
    "Choose a subclass"
   ],
   "3": [],
   "4": [
    "Feat",
    "Wild Shape Improvement"
   ],
   "5": [
    "Wild Strike"
   ],
   "6": [
    "Subclass feature"
   ],
   "7": [],
   "8": [
    "Feat",
    "Wild Shape Improvement"
   ],
   "9": [],
   "10": [
    "Subclass feature",
    "Improved Wild Strike"
   ],
   "11": [],
   "12": [
    "Feat",
    "Wild Shape Improvement"
   ]
  },
  "subclassLevel": 2,
  "subclasses": {
   "Circle of the Land": {
    "2": [
     "Natural Recovery",
     "Bonus Cantrip"
    ],
    "3": [
     "2nd Level Circle of the Land Spells"
    ],
    "5": [
     "3rd Level Circle of the Land Spells"
    ],
    "6": [
     "Land's Stride: Difficult Terrain",
     "Land's Stride: Advantage",
     "Land's Stride: Plants"
    ],
    "7": [
     "4th Level Circle of the Land Spells"
    ],
    "9": [
     "5th Level Circle of the Land Spells"
    ],
    "10": [
     "Nature's Ward"
    ]
   },
   "Circle of the Moon": {
    "2": [
     "Lunar Mend",
     "Combat Wild Shape",
     "Wild Shape: Bear"
    ],
    "4": [
     "Wild Shape: Dire Raven"
    ],
    "6": [
     "Primal Strike"
    ],
    "8": [
     "Wild Shape: Sabre-Toothed Tiger"
    ],
    "10": [
     "Wild Shape: Air Myrmidon",
     "Wild Shape: Earth Myrmidon",
     "Wild Shape: Fire Myrmidon",
     "Wild Shape: Water Myrmidon"
    ]
   },
   "Circle of the Spores": {
    "2": [
     "Bone Chill",
     "Halo of Spores",
     "Symbiotic Entity"
    ],
    "3": [
     "2nd Level Circle of the Spores Spells",
     "Blindness",
     "Detect Thoughts"
    ],
    "5": [
     "3rd Level Circle of the Spores Spells",
     "Animate Dead",
     "Gaseous Form"
    ],
    "6": [
     "Halo of Spores",
     "Fungal Infestation"
    ],
    "7": [
     "4th Level Circle of the Spores Spells",
     "Blight",
     "Confusion"
    ],
    "9": [
     "5th Level Circle of the Spores Spells",
     "Cloudkill",
     "Contagion"
    ],
    "10": [
     "Halo of Spores",
     "Spreading Spores"
    ]
   },
   "Circle of the Stars": {
    "2": [
     "Guidance",
     "Starry Form",
     "Circle of the Stars spells",
     "Guiding Bolt",
     "Star Map: Guiding Bolt"
    ],
    "5": [
     "Dazzling Breath"
    ],
    "6": [
     "Cosmic Omen",
     "Cosmic Omen of Weal: Attack Roll",
     "Cosmic Omen of Woe: Attack Roll",
     "Cosmic Omen of Weal: Saving Throw",
     "Cosmic Omen of Woe: Saving Throw"
    ],
    "10": [
     "Twinkling Constellations"
    ]
   }
  }
 },
 "Fighter": {
  "levels": {
   "1": [
    "Second Wind",
    "Fighting Style"
   ],
   "2": [
    "Action Surge"
   ],
   "3": [
    "Choose a subclass"
   ],
   "4": [
    "Feat"
   ],
   "5": [
    "Extra Attack"
   ],
   "6": [
    "Feat"
   ],
   "7": [
    "Subclass feature"
   ],
   "8": [
    "Feat"
   ],
   "9": [
    "Indomitable"
   ],
   "10": [
    "Subclass feature"
   ],
   "11": [
    "Improved Extra Attack"
   ],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 3,
  "subclasses": {
   "Arcane Archer": {
    "3": [
     "Arcane Archer Lore",
     "Gain a Cantrip",
     "Guidance",
     "Light",
     "True Strike",
     "Arcane Shots"
    ],
    "7": [
     "Curving Shot",
     "Magic Arrow",
     "Arcane Shots"
    ],
    "10": [
     "Arcane Shots"
    ]
   },
   "Battle Master": {
    "3": [
     "Manoeuvres"
    ],
    "7": [
     "Choose 2 additional manoeuvres."
    ],
    "10": [
     "Improved Combat Superiority",
     "Choose 2 additional manoeuvres."
    ]
   },
   "Champion": {
    "3": [
     "Improved Critical Hit"
    ],
    "7": [
     "Remarkable Athlete: Jump",
     "Remarkable Athlete: Proficiency"
    ],
    "10": [
     "Fighting Style",
     "Choose 1 additional fighting style"
    ]
   },
   "Eldritch Knight": {
    "3": [
     "Weapon Bond"
    ],
    "4": [
     "Spellcasting"
    ],
    "7": [
     "Spellcasting",
     "War Magic"
    ],
    "10": [
     "Eldritch Strike",
     "Spellcasting"
    ]
   }
  }
 },
 "Monk": {
  "levels": {
   "1": [
    "Unarmoured Defence",
    "Martial Arts: Dextrous Attacks",
    "Martial Arts: Deft Strikes",
    "Martial Arts: Bonus Unarmed Strike",
    "Flurry of Blows"
   ],
   "2": [
    "Unarmoured Movement",
    "Patient Defence",
    "Step of the Wind: Dash",
    "Step of the Wind: Disengage"
   ],
   "3": [
    "Choose a subclass",
    "Deflect Missiles"
   ],
   "4": [
    "Feat",
    "Slow Fall"
   ],
   "5": [
    "Extra Attack",
    "Stunning Strike",
    "Stunning Strike (Unarmed)"
   ],
   "6": [
    "Ki-Empowered Strikes",
    "Subclass feature",
    "Improved Unarmoured Movement"
   ],
   "7": [
    "Evasion",
    "Stillness of Mind"
   ],
   "8": [
    "Feat"
   ],
   "9": [
    "Advanced Unarmoured Movement",
    "Subclass feature"
   ],
   "10": [
    "Purity of Body",
    "Improved Unarmoured Movement"
   ],
   "11": [
    "Subclass feature"
   ],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 3,
  "subclasses": {
   "Way of the Drunken Master": {
    "3": [
     "Cheeky Tipple",
     "Drunken Performance",
     "Drunken Technique",
     "Flurry of Blows is replaced by Drunken Technique"
    ],
    "4": [
     "Intoxicating Strike",
     "Intoxicating Strike (Bonus Action)",
     "Life of the Party"
    ],
    "6": [
     "Leap to Your Feet",
     "Redirect Attack"
    ],
    "9": [
     "Sobering Realisation"
    ],
    "11": [
     "Drunkard's Luck"
    ]
   },
   "Way of the Four Elements": {
    "3": [
     "You can use ki to power magical spells that harness the elements.",
     "Harmony of Fire and Water"
    ],
    "6": [
     "Select 1 spell from the spell list.",
     "Clench of the North Wind",
     "Embrace of the Inferno",
     "Gong of the Summit"
    ],
    "9": [
     "Select 1 spell from the spell list.",
     "Improved Elemental Casting"
    ],
    "11": [
     "Select 1 spell from the spell list.",
     "Flames of the Phoenix",
     "Mist Stance",
     "Ride the Wind"
    ]
   },
   "Way of the Open Hand": {
    "3": [
     "Flurry of Blows",
     "Flurry of Blows: Topple",
     "Flurry of Blows: Stagger",
     "Flurry of Blows: Push"
    ],
    "6": [
     "Manifestation of Body",
     "Manifestation of Mind",
     "Manifestation of Soul",
     "Wholeness of Body"
    ],
    "9": [
     "Ki Resonation: Punch",
     "Ki Resonation: Punch (Bonus Action)",
     "Ki Resonation: Blast"
    ],
    "11": [
     "Tranquillity"
    ]
   },
   "Way of Shadow": {
    "3": [
     "Minor Illusion",
     "Shadow Arts: Hide",
     "Shadow Arts: Pass Without Trace",
     "Shadow Arts: Darkness",
     "Shadow Arts: Darkvision",
     "Shadow Arts: Silence"
    ],
    "5": [
     "Cloak of Shadows"
    ],
    "6": [
     "Shadow Step"
    ],
    "11": [
     "Shadow Strike",
     "Shadow Strike: Unarmed"
    ]
   }
  }
 },
 "Paladin": {
  "levels": {
   "1": [
    "Divine Sense",
    "Lay on Hands",
    "Channel Oath",
    "Choose a subclass"
   ],
   "2": [
    "Fighting Style",
    "Spellcasting",
    "Divine Smite"
   ],
   "3": [
    "Divine Health",
    "Subclass Feature"
   ],
   "4": [
    "Feat"
   ],
   "5": [
    "Extra Attack"
   ],
   "6": [
    "Aura of Protection"
   ],
   "7": [
    "Subclass Feature"
   ],
   "8": [
    "Feat"
   ],
   "9": [
    "Subclass Feature"
   ],
   "10": [
    "Aura of Courage"
   ],
   "11": [
    "Improved Divine Smite"
   ],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 1,
  "subclasses": {
   "Oath of Devotion": {
    "1": [
     "Oath of Devotion Tenets",
     "Holy Rebuke"
    ],
    "3": [
     "Sacred Weapon",
     "Turn the Unholy",
     "Oath Spells",
     "Protection from Evil and Good",
     "Sanctuary"
    ],
    "5": [
     "Oath Spells",
     "Lesser Restoration",
     "Silence"
    ],
    "7": [
     "Aura of Devotion"
    ],
    "9": [
     "Oath Spells",
     "Remove Curse",
     "Beacon of Hope"
    ]
   },
   "Oath of the Ancients": {
    "1": [
     "Oath of the Ancients Tenets",
     "Healing Radiance"
    ],
    "3": [
     "Nature's Wrath",
     "Turn the Faithless",
     "Oath Spells",
     "Speak with Animals",
     "Ensnaring Strike"
    ],
    "5": [
     "Oath Spells",
     "Misty Step",
     "Moonbeam"
    ],
    "7": [
     "Aura of Warding"
    ],
    "9": [
     "Oath Spells",
     "Protection from Energy",
     "Plant Growth"
    ]
   },
   "Oath of the Crown": {
    "1": [
     "Oath of the Crown Tenets",
     "Righteous Clarity"
    ],
    "3": [
     "Champion Challenge",
     "Turn the Tide",
     "Oath Spells",
     "Command",
     "Compelled Duel"
    ],
    "5": [
     "Oath Spells",
     "Warding Bond",
     "Spiritual Weapon"
    ],
    "7": [
     "Divine Allegiance"
    ],
    "9": [
     "Oath Spells",
     "Spirit Guardians",
     "Crusader's Mantle"
    ]
   },
   "Oath of Vengeance": {
    "1": [
     "Oath of Vengeance Tenets",
     "Inquisitor's Might"
    ],
    "3": [
     "Abjure Enemy",
     "Vow of Enmity",
     "Oath Spells",
     "Bane",
     "Hunter's Mark"
    ],
    "5": [
     "Oath Spells",
     "Misty Step",
     "Hold Person"
    ],
    "7": [
     "Relentless Avenger"
    ],
    "9": [
     "Oath Spells",
     "Haste",
     "Protection from Energy"
    ]
   },
   "Oathbreaker": {
    "1": [
     "Spiteful Suffering"
    ],
    "3": [
     "Control Undead",
     "Dreadful Aspect",
     "Oath Spells",
     "Hellish Rebuke",
     "Inflict Wounds"
    ],
    "5": [
     "Oath Spells",
     "Crown of Madness",
     "Darkness"
    ],
    "7": [
     "Aura of Hate"
    ],
    "9": [
     "Oath Spells",
     "Bestow Curse",
     "Animate Dead"
    ]
   }
  }
 },
 "Ranger": {
  "levels": {
   "1": [
    "Favoured Enemy",
    "Natural Explorer"
   ],
   "2": [
    "Fighting Style",
    "Spellcasting"
   ],
   "3": [
    "Choose a subclass"
   ],
   "4": [
    "Feat"
   ],
   "5": [
    "Extra Attack",
    "Subclass Feature"
   ],
   "6": [
    "Favoured Enemy",
    "Natural Explorer"
   ],
   "7": [
    "Subclass Feature"
   ],
   "8": [
    "Feat",
    "Land's Stride: Difficult Terrain"
   ],
   "9": [],
   "10": [
    "Favoured Enemy",
    "Natural Explorer",
    "Hide in Plain Sight"
   ],
   "11": [
    "Subclass Feature"
   ],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 3,
  "subclasses": {
   "Beast Master": {
    "3": [
     "Ranger's Companion",
     "New abilities"
    ],
    "5": [
     "Companion's Bond",
     "New abilities"
    ],
    "7": [
     "Exceptional Training"
    ],
    "8": [
     "Upgraded Hp for your companion."
    ],
    "11": [
     "Bestial Fury",
     "New abilities"
    ]
   },
   "Gloom Stalker": {
    "3": [
     "Disguise Self",
     "Umbral Shroud",
     "Superior Darkvision",
     "Dread Ambusher"
    ],
    "5": [
     "Misty Step"
    ],
    "7": [
     "Iron Mind"
    ],
    "9": [
     "Fear"
    ],
    "11": [
     "Stalker's Flurry"
    ]
   },
   "Hunter": {
    "3": [
     "Hunter's Prey"
    ],
    "7": [
     "Defensive Tactics"
    ],
    "11": [
     "Volley",
     "Whirlwind Attack"
    ]
   },
   "Swarmkeeper": {
    "3": [
     "Prey's Scent (Swarmkeeper)",
     "Gathered Swarm",
     "Mage Hand",
     "Faerie Fire"
    ],
    "5": [
     "Web"
    ],
    "7": [
     "Writhing Tide"
    ],
    "9": [
     "Gaseous Form"
    ],
    "11": [
     "Mighty Swarm"
    ]
   }
  }
 },
 "Rogue": {
  "levels": {
   "1": [
    "Expertise",
    "Sneak Attack"
   ],
   "2": [
    "Cunning Action: Dash",
    "Cunning Action: Disengage",
    "Cunning Action: Hide"
   ],
   "3": [
    "Choose a subclass"
   ],
   "4": [
    "Feat"
   ],
   "5": [
    "Uncanny Dodge"
   ],
   "6": [
    "Expertise"
   ],
   "7": [
    "Evasion"
   ],
   "8": [
    "Feat"
   ],
   "9": [
    "Subclass feature"
   ],
   "10": [
    "Feat"
   ],
   "11": [
    "Reliable Talent"
   ],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 3,
  "subclasses": {
   "Arcane Trickster": {
    "3": [
     "Mage Hand Legerdemain",
     "Mage Hand"
    ],
    "4": [
     "Spellcasting"
    ],
    "7": [
     "Spellcasting"
    ],
    "9": [
     "Magical Ambush"
    ],
    "10": [
     "Spellcasting"
    ]
   },
   "Assassin": {
    "3": [
     "Assassin's Alacrity",
     "Assassinate: Ambush",
     "Assassinate: Initiative"
    ],
    "9": [
     "Infiltration Expertise"
    ]
   },
   "Swashbuckler": {
    "3": [
     "Fancy Footwork",
     "Rakish Audacity",
     "Normal Sneak Attack is replaced by Rakish Sneak Attack"
    ],
    "4": [
     "Dirty Tricks",
     "Learn the following Dirty Tricks"
    ],
    "9": [
     "Panache"
    ]
   },
   "Thief": {
    "3": [
     "Fast Hands",
     "Second-Story Work"
    ],
    "9": [
     "Supreme Sneak"
    ]
   }
  }
 },
 "Sorcerer": {
  "levels": {
   "1": [
    "Spellcasting",
    "Choose a subclass"
   ],
   "2": [
    "Metamagic",
    "Create Spell Slot",
    "Create Sorcery Points"
   ],
   "3": [
    "Metamagic"
   ],
   "4": [
    "Feat"
   ],
   "5": [],
   "6": [
    "Subclass feature"
   ],
   "7": [],
   "8": [
    "Feat"
   ],
   "9": [],
   "10": [
    "Metamagic"
   ],
   "11": [
    "Subclass feature"
   ],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 1,
  "subclasses": {
   "Draconic Bloodline": {
    "1": [
     "Draconic Resilience",
     "Draconic Resilience: Hit Points",
     "Draconic Ancestry (Choose 1)"
    ],
    "6": [
     "Elemental Affinity: Damage",
     "Elemental Affinity: Resistance"
    ],
    "11": [
     "Fly (class action)"
    ]
   },
   "Shadow Magic": {
    "1": [
     "Eyes of the Dark",
     "Strength of the Grave"
    ],
    "3": [
     "Darkness",
     "Eyes of the Dark: Darkness"
    ],
    "6": [
     "Hound of Ill Omen"
    ],
    "11": [
     "Shadow Walk"
    ]
   },
   "Storm Sorcery": {
    "1": [
     "Tempestuous Magic"
    ],
    "6": [
     "Heart of the Storm",
     "Heart of the Storm: Resistance",
     "Storm Spells",
     "Thunderwave",
     "Create or Destroy Water",
     "Gust of Wind",
     "Sleet Storm",
     "Call Lightning"
    ],
    "11": [
     "Storm's Fury"
    ]
   },
   "Wild Magic (sorcerer subclass)": {
    "1": [
     "Wild Magic",
     "Tides of Chaos"
    ],
    "6": [
     "Bend Luck"
    ],
    "11": [
     "Controlled Chaos"
    ]
   }
  }
 },
 "Warlock": {
  "levels": {
   "1": [
    "Pact Magic",
    "Choose a Subclass"
   ],
   "2": [
    "Eldritch Invocations (+2)"
   ],
   "3": [
    "Pact Boon"
   ],
   "4": [
    "Feat"
   ],
   "5": [
    "Deepened Pact",
    "Eldritch Invocations (+1)"
   ],
   "6": [
    "Subclass feature"
   ],
   "7": [
    "Eldritch Invocations (+1)"
   ],
   "8": [
    "Feat"
   ],
   "9": [
    "Eldritch Invocations (+1)"
   ],
   "10": [
    "Subclass feature"
   ],
   "11": [
    "Mystic Arcanum (6th level spell)"
   ],
   "12": [
    "Feat",
    "Eldritch Invocations (+1)"
   ]
  },
  "subclassLevel": 1,
  "subclasses": {
   "The Archfey": {
    "1": [
     "Fey Presence",
     "Expanded Spell List",
     "Faerie Fire",
     "Sleep"
    ],
    "3": [
     "Expanded Spell List",
     "Calm Emotions",
     "Phantasmal Force"
    ],
    "5": [
     "Expanded Spell List",
     "Blink",
     "Plant Growth"
    ],
    "6": [
     "Misty Escape"
    ],
    "7": [
     "Expanded Spell List",
     "Dominate Beast",
     "Greater Invisibility"
    ],
    "9": [
     "Expanded Spell List",
     "Dominate Person",
     "Seeming"
    ],
    "10": [
     "Beguiling Defences"
    ]
   },
   "The Fiend": {
    "1": [
     "Dark One's Blessing",
     "Expanded Spell List",
     "Burning Hands",
     "Command"
    ],
    "3": [
     "Expanded Spell List",
     "Blindness",
     "Scorching Ray"
    ],
    "5": [
     "Expanded Spell List",
     "Fireball",
     "Stinking Cloud"
    ],
    "6": [
     "Dark One's Own Luck"
    ],
    "7": [
     "Expanded Spell List",
     "Wall of Fire",
     "Fire Shield"
    ],
    "9": [
     "Expanded Spell List",
     "Cone of Cold",
     "Flame Strike"
    ],
    "10": [
     "Fiendish Resilience"
    ]
   },
   "The Great Old One": {
    "1": [
     "Mortal Reminder",
     "Expanded Spell List",
     "Dissonant Whispers",
     "Tasha's Hideous Laughter"
    ],
    "3": [
     "Expanded Spell List",
     "Detect Thoughts",
     "Phantasmal Force"
    ],
    "5": [
     "Expanded Spell List",
     "Bestow Curse",
     "Slow"
    ],
    "6": [
     "Entropic Ward"
    ],
    "7": [
     "Expanded Spell List",
     "Dominate Beast",
     "Evard's Black Tentacles"
    ],
    "9": [
     "Expanded Spell List",
     "Dominate Person",
     "Telekinesis"
    ],
    "10": [
     "Thought Shield: Psychic Resistance",
     "Thought Shield: Psychic Reflection"
    ]
   },
   "The Hexblade": {
    "1": [
     "Hex Warrior",
     "Bind Hexed Weapon",
     "Hexblade's Curse",
     "Expanded Spell List",
     "Shield",
     "Wrathful Smite"
    ],
    "3": [
     "Expanded Spell List",
     "Blur",
     "Branding Smite"
    ],
    "5": [
     "Expanded Spell List",
     "Blink",
     "Elemental Weapon"
    ],
    "6": [
     "Accursed Spectre"
    ],
    "7": [
     "Expanded Spell List",
     "Phantasmal Killer",
     "Staggering Smite",
     "Dominate Beast",
     "Greater Invisibility"
    ],
    "9": [
     "Expanded Spell List",
     "Banishing Smite",
     "Cone of Cold"
    ],
    "10": [
     "Armour of Hexes"
    ]
   }
  }
 },
 "Wizard": {
  "levels": {
   "1": [
    "Spellcasting",
    "Arcane Recovery",
    "24px Transcribing scrolls"
   ],
   "2": [
    "Choose a subclass"
   ],
   "3": [],
   "4": [
    "Feat"
   ],
   "5": [],
   "6": [
    "Subclass feature"
   ],
   "7": [],
   "8": [
    "Feat"
   ],
   "9": [],
   "10": [
    "Subclass feature"
   ],
   "11": [],
   "12": [
    "Feat"
   ]
  },
  "subclassLevel": 2,
  "subclasses": {
   "Abjuration School": {
    "2": [
     "Abjuration Savant",
     "Arcane Ward"
    ],
    "6": [
     "Projected Ward"
    ],
    "10": [
     "Improved Abjuration"
    ]
   },
   "Bladesinging": {
    "2": [
     "Bladesong",
     "Training in War and Song"
    ],
    "5": [
     "Bladesong"
    ],
    "6": [
     "Extra Attack"
    ],
    "9": [
     "Bladesong"
    ],
    "10": [
     "Song of Defence"
    ]
   },
   "Conjuration School": {
    "2": [
     "Conjuration Savant",
     "Minor Conjuration: Create Water"
    ],
    "6": [
     "Benign Transposition: Teleport"
    ],
    "10": [
     "Focused Conjuration"
    ]
   },
   "Divination School": {
    "2": [
     "Divination Savant",
     "Portent"
    ],
    "6": [
     "Expert Divination"
    ],
    "10": [
     "Third Eye: Darkvision",
     "Third Eye: See Invisibility"
    ]
   },
   "Enchantment School": {
    "2": [
     "Enchantment Savant",
     "Hypnotic Gaze"
    ],
    "6": [
     "Instinctive Charm"
    ],
    "10": [
     "Split Enchantment"
    ]
   },
   "Evocation School": {
    "2": [
     "Evocation Savant",
     "Sculpt Spells"
    ],
    "6": [
     "Potent Cantrip"
    ],
    "10": [
     "Empowered Evocation"
    ]
   },
   "Illusion School": {
    "2": [
     "Illusion Savant",
     "Improved Minor Illusion"
    ],
    "6": [
     "See Invisibility (class action)"
    ],
    "10": [
     "Illusory Self"
    ]
   },
   "Necromancy School": {
    "2": [
     "Necromancy Savant",
     "Grim Harvest"
    ],
    "6": [
     "Undead Thralls: Animate Dead",
     "Undead Thralls: Additional Undead",
     "Undead Thralls: Better Summons"
    ],
    "10": [
     "Inured to Undeath"
    ]
   },
   "Transmutation School": {
    "2": [
     "Transmutation Savant",
     "Experimental Alchemy"
    ],
    "6": [
     "Transmuter's Stone",
     "Transmuter's Stone: Constitution",
     "Transmuter's Stone: Darkvision",
     "Transmuter's Stone: Speed",
     "Transmuter's Stone: Acid Resistance",
     "Transmuter's Stone: Cold Resistance",
     "Transmuter's Stone: Fire Resistance",
     "Transmuter's Stone: Lightning Resistance",
     "Transmuter's Stone: Thunder Resistance"
    ],
    "10": [
     "Shapechanger"
    ]
   }
  }
 }
};
window.BG3_FEATS = [
  ["Ability Improvement", "Increase one ability score by 2, or two ability scores by 1, up to a maximum of 20."],
  ["Actor", "Your Charisma ability score increases by 1, to a maximum of 20.; You gain expertise in Deception and Performance."],
  ["Alert", "You gain a +5 bonus to initiative and can't be Surprised."],
  ["Athlete", "Your Strength or Dexterity ability score increases by 1, to a maximum of 20.; When you are Prone, standing up uses significantly less movement.; Your Jump distance also increases by 50%."],
  ["Charger", "Charge forward and slam your weapon into the first enemy in your way without provoking Opportunity Attack.; Charge forward and Shove the first enemy in your way without provoking Opportunity Attack.; Shove distance depends on your Strength and the target's weight."],
  ["Crossbow Expert", "When you make crossbow attacks within melee range, the attack rolls do not have Disadvantage.; Your Piercing Shot also inflicts Gaping Wounds for twice as long."],
  ["Defensive Duellist", "When you are attacked with a melee attack while wielding a Finesse weapon you are proficient in, you can use a Reaction to increase your Armour Class by your proficiency bonus, possibly causing the attack to miss. Requires Dexterity to be at least 13."],
  ["Dual Wielder", "You can use Two-Weapon Fighting even if your weapons aren't Light.; You cannot dual-wield Two-Handed weapons.; You have a +1 bonus to Armour Class while wielding a melee weapon in each hand."],
  ["Dungeon Delver", "You gain Advantage on Perception checks made to detect hidden objects and on Saving Throws made to avoid or resist traps.; You gain resistance to the damage dealt by traps."],
  ["Durable", "Your Constitution ability score increases by 1, to a maximum of 20.; Regain full hit points every time you take a short rest."],
  ["Elemental Adept", "Elemental Adept; Your spells and attacks ignore resistance to a damage type of your choice. In addition, when you deal that type of damage with a spell, you cannot roll a 1.; Damage resistance options are one of the following:; Elemental Adept: Acid; Elemental Adept: Cold; Elemental Adept: Lightning; Elemental Adept:…"],
  ["Great Weapon Master", "When an attack with a melee weapon lands a Critical Hit or kills a creature, you can make another melee weapon attack as a Bonus that turn.; When attacking with a Two-Handed or Versatile melee weapon (in both hands) that you are Proficient with, Attack Rolls take a -5 penalty, but their damage increases by 10."],
  ["Heavily Armoured", "Your Strength ability score increases by 1, to a maximum of 20.; Gain Proficiency with Heavy Armour."],
  ["Heavy Armour Master", "Your Strength ability score increases by 1, to a maximum of 20.; Incoming damage from non-magical attacks also decreases by 3 while you're wearing heavy armour."],
  ["Lightly Armoured", "Your Strength or Dexterity ability score increases by 1, to a maximum of 20.; Gain Proficiency with Light Armour."],
  ["Lucky", "You gain 3 Luck Points that recharge after a Long Rest, which you can use to gain Advantage on Attack Rolls, Checks, or Saving Throws, or to make an enemy reroll their Attack Roll."],
  ["Mage Slayer", "When a creature casts a Spell within melee range of you, you have Advantage on any Saving Throws against it.; You can use a Reaction to immediately make an attack against the caster if it casts a spell within 1.5m / 5ft of you.; Enemies you hit have Disadvantage when making Saving Throws to maintain their Concentratio…"],
  ["Magic Initiate: Bard", "Learn 2 Cantrips and a 1st-level Spell from the Bard spell list. You can cast the 1st-level Spell once per Long Rest. Your Spellcasting Ability for all three spells is Charisma."],
  ["Magic Initiate: Cleric", "Learn 2 Cantrips and a 1st-level Spell from the Cleric spell list. You can cast the 1st-level Spell once per Long Rest. Your Spellcasting Ability for all three spells is Wisdom."],
  ["Magic Initiate: Druid", "Learn 2 Cantrips and a 1st-level Spell from the Druid spell list. You can cast the 1st-level Spell once per Long Rest. Your Spellcasting Ability for all three spells is Wisdom."],
  ["Magic Initiate: Sorcerer", "Learn 2 Cantrips and a 1st-level Spell from the Sorcerer spell list. You can cast the 1st-level Spell once per Long Rest. Your Spellcasting Ability for all three spells is Charisma."],
  ["Magic Initiate: Warlock", "Learn 2 Cantrips and a 1st-level Spell from the Warlock spell list. You can cast the 1st-level Spell once per Long Rest. Your Spellcasting Ability for all three spells is Charisma."],
  ["Magic Initiate: Wizard", "Learn 2 Cantrips and a 1st-level Spell from the Wizard spell list. You can cast the 1st-level Spell once per Long Rest. Your Spellcasting Ability for all three spells is Intelligence."],
  ["Martial Adept", "Learn two Manoeuvres from the Battle Master archetype and receive 1 (additional) Superiority Die to fuel them. You regain expended Superiority Dice after a Short or Long Rest."],
  ["Medium Armour Master", "When you wear medium armour, it doesn't impose Disadvantage on Stealth checks. The bonus to Armour Class you can gain from your Dexterity modifier also becomes +3 instead of +2."],
  ["Mobile", "Your Movement Speed increases by 3 m.; When you use the Dash action, Difficult Terrain doesn't slow you down.; If you move after making a melee attack, you don't provoke an Opportunity Attack from that target."],
  ["Moderately Armoured", "Requires Light Armour Proficiency.; Your Strength or Dexterity ability score increases by 1, to a maximum of 20.; Gain Proficiency with Medium Armour and Shields."],
  ["Performer", "Your Charisma ability score increases by 1, to a maximum of 20.; Gain Musical Instrument Proficiency."],
  ["Polearm Master", "When attacking with a Glaives, Halberds, Pikes, Quarterstaves, or Spears, you can use a Bonus to attack with the butt of your weapon.; You can also make an Opportunity Attack when a target comes within range."],
  ["Resilient", "Resilient; You increase an Ability by 1, to a maximum of 20.; Gain Proficiency in that ability's Saving Throws.; The available passive features are:; Resilient: Strength; Resilient: Dexterity; Resilient: Constitution; Resilient: Intelligence; Resilient: Wisdom; Resilient: Charisma"],
  ["Ritual Caster", "You learn two Ritual Spell spells of your choice."],
  ["Savage Attacker", "When making melee weapon attacks, you roll your damage dice twice and use the highest result."],
  ["Sentinel", "When an enemy in melee range attacks an ally, you can use a Reaction to make a weapon attack against that enemy. Target ally must not have the Sentinel feat.; When you hit a creature with an Opportunity Attack, it can no longer move for the rest of its turn.; :* You gain Advantage on Opportunity Attacks."],
  ["Sharpshooter", "Your ranged weapon attacks are not penalized for High Ground Rules.; Ranged weapon attacks with weapons you are Proficient with have a -5 penalty to their Attack Roll, but deal an additional 10 damage."],
  ["Shield Master", "Gain a +2 bonus to Dexterity Saving Throw when wielding a Shield.; If a Spell forces you to make a Dexterity Saving Throw, you can use your Reaction to shield yourself and diminish the effect's damage.; - On a failed save, you only take half damage.; - On a successful save, you don't take any damage, even if you norma…"],
  ["Skilled", "You gain Proficiency in 3 Skills of your choice."],
  ["Spell Sniper", "You learn a cantrip, and the number you need to roll a Critical Hit while attacking with a Spell is reduced by 1. This effect can stack."],
  ["Tavern Brawler", "Your Strength or Constitution ability score increases by 1, to a maximum of 20.; When you make an unarmed attack, use an improvised weapon, or throw something, your strength modifier is added twice to the damage and Attack Roll."],
  ["Tough", "Hit Point maximum increased by 2 for each level."],
  ["War Caster", "You gain Advantage on Saving Throws to maintain Concentration on a Spell.; You can also use a Reaction to cast Shocking Grasp at a target moving out of melee range."],
  ["Weapon Master", "Your Strength or Dexterity ability score increases by 1, to a maximum of 20.; Gain Proficiency with four Weapon types of your choice."]
];
