"""Builds conditions.js: the conditions the damage test knows how to play (Prone, Stunned, Paralysed, Frightened,
Blinded, Restrained and the others whose page says the same kind of thing).

    py tools/update_conditions.py

Run it after update_spells.py, update_enemies.py and update_consumables.py: the names come from the conditions
those files mention (the ones spells leave, the ones enemies inflict, the ones a weapon coating carries), plus the
few a class feature or a manoeuvre inflicts. Each condition's page on bg3.wiki is read for what it does, and only
what the test can use is kept, as flags (see condition_flags in update_enemies.py); a condition with none is left out.
"""
import io, json, os, re, sys, time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from update_items import page_texts, record, short
from update_enemies import condition_flags

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "conditions.js")
# inflicted by features of the classes (Trip Attack, Menacing Attack, Stunning Strike…) and by the rules themselves
ALWAYS = ["Prone", "Stunned", "Paralysed", "Frightened", "Blinded", "Restrained", "Surprised", "Poisoned", "Sleeping", "Goaded", "Distracted", "Evasive Footwork"]


def array(name, var):
    text = io.open(os.path.join(ROOT, name), encoding="utf-8").read()
    return json.JSONDecoder().raw_decode(text[text.index(var + " = ") + len(var) + 3:])[0]


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    names = set(ALWAYS)
    for s in array("spells.js", "window.BG3_SPELLS"):
        names |= {c[0] for c in s.get("cn", [])}
    for e in array("enemies.js", "window.BG3_ENEMIES"):
        names |= {a["cd"][0] for a in e.get("acts", []) + e.get("rx", []) if a.get("cd")}
    for c in array("consumables.js", "window.BG3_CONSUMABLES"):
        names |= set(c.get("cs", []))
    pages = page_texts({n + " (Condition)" for n in names} | names)
    out = {}
    for n in sorted(names):
        flags, said = condition_flags(pages.get(n + " (Condition)") or pages.get(n) or "")
        if flags:
            out[n] = {"x": short(said, 400), "f": flags}
    body = ",\n".join("  " + json.dumps(k, ensure_ascii=False) + ":" + json.dumps(v, ensure_ascii=False, separators=(",", ":")) for k, v in out.items())
    js = ("// The conditions the damage test plays. Generated by tools/update_conditions.py from bg3.wiki; do not edit by hand,\n"
          "// re-run the script instead.\n"
          "// name: x what its page says · f what the test uses of it: skip no actions · nr no reactions · adv attacks against\n"
          "//   it have Advantage (near: only from within 3 m) · crit hits from within 3 m are critical · dis its attack rolls\n"
          "//   have Disadvantage · fail saves it fails · sd saves it rolls with Disadvantage · drop ends Concentration\n"
          "//   · tk start: counts down at the start of a turn · src 1: counts down on the turn of whoever caused it\n"
          "//   · rep the save repeated each turn to shake it off (same: the one that let it in) · wake 1: taking damage ends it\n"
          "//   · ally 1: the Advantage is only for the allies of whoever caused it · once 1: spent by the next attack\n"
          "//   · guard 1: melee attacks against it have Disadvantage · still 1: it cannot move\n"
          f"window.BG3_CONDITIONS_DATE = {json.dumps(time.strftime('%Y-%m-%d'))};\n"
          "window.BG3_CONDITIONS = {\n" + body + "\n};\n")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(js)
    record("conditions")
    print(f"Wrote {len(out)} of {len(names)} conditions to {OUT}")
    for k, v in out.items():
        print("  ", k, v["f"])


if __name__ == "__main__":
    main()
