"""Rebuild consumables.js from bg3.wiki: elixirs, potions, arrows, coatings and grenades, with what each one does.

Run from anywhere:  py tools/update_consumables.py
Needs only the Python standard library and an internet connection. Takes a few seconds.
"""
import io, json, os, re, sys, time

from update_items import RARITY, THUMBS, THUMB_SIZE, api, clean, drop_empty, field, record, remember_thumb, short

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "consumables.js")
KINDS = [("Elixirs", "Elixir"), ("Potions", "Potion"), ("Arrows", "Arrow"), ("Coatings", "Coating"), ("Grenades", "Grenade")]


def category_pages(category):
    out, cont = {}, {}
    while True:
        d = api(action="query", generator="categorymembers", gcmtitle="Category:" + category, gcmnamespace=0, gcmlimit=50,
                prop="revisions|pageimages", rvprop="content", rvslots="main", piprop="thumbnail", pithumbsize=THUMB_SIZE, pilimit=50, **cont)
        for p in d.get("query", {}).get("pages", {}).values():
            remember_thumb(p)
            if "revisions" in p:
                out[p["title"]] = p["revisions"][0]["slots"]["main"]["*"]
        if "continue" not in d:
            return out
        cont = d["continue"]


def effect(w):
    """What the item does when used: the first lines of the effect field, without the thrown variant."""
    text = field(w, "effect")
    text = re.split(r"\n\s*\{\{\s*InfoBlob", text, maxsplit=1, flags=re.I)[0]  # what follows is the thrown variant
    # the bullet list of the wiki becomes sentences; range and area icons leave stray words behind
    text = re.sub(r"\.?\s*;\s*", ". ", clean(text)).strip().rstrip(".") + "."
    text = re.sub(r"\w+ Icon\.(?:png|webp)", "", re.sub(r"(?<=\. )(?:ranged|melee)\. ", "", text))
    return short(re.sub(r"\s+", " ", text), 300)


def duration(value):
    value = clean(value)
    return (value + (" turn" if value == "1" else " turns")) if value.isdigit() else value


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    items = []
    for category, kind in KINDS:
        print(f"Reading {category}…")
        for title, w in category_pages(category).items():
            m = re.search(r"\{\{\s*misc\s*item\s*page", w, re.I)
            if not m or re.search(r"\{\{\s*unobtainable", w, re.I):
                continue
            w = w[m.start():]
            items.append({"n": title, "t": kind, "r": RARITY.get(clean(field(w, "rarity")).lower(), "common"), "x": effect(w),
                          "du": duration(field(w, "condition duration")), "uc": {"bonus": "Bonus action"}.get(clean(field(w, "usage cost")).lower(), clean(field(w, "usage cost")).capitalize()), "i": THUMBS.get(title, ""),
                          "h": short(clean(field(w, "where to find")), 200), "pr": clean(field(w, "price"))})
    seen = set()
    items = [it for it in sorted(items, key=lambda it: it["n"].lower()) if not (it["n"] in seen or seen.add(it["n"]))]
    for it in items:
        drop_empty(it, keep=("n", "t"))
    body = ",\n".join("  " + json.dumps(it, ensure_ascii=False, separators=(",", ":")) for it in items)
    js = ("// Consumables for the planner: elixirs, potions, arrows, coatings and grenades. Generated by tools/update_consumables.py\n"
          "// from bg3.wiki; do not edit by hand, re-run the script instead.\n"
          "// n name · t kind · r rarity · x what it does · du how long it lasts · uc what using it takes (Action, Bonus action) · i picture · h where to get it · pr price\n"
          f"window.BG3_CONSUMABLES_DATE = {json.dumps(time.strftime('%Y-%m-%d'))};\n"
          "window.BG3_CONSUMABLES = [\n" + body + "\n];\n")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(js)
    record("consumables")
    by_kind = {}
    for it in items:
        by_kind[it["t"]] = by_kind.get(it["t"], 0) + 1
    print(f"Wrote {len(items)} consumables to {OUT} ({len(js) // 1024} KB):", by_kind)
    print("  without effect text:", [it["n"] for it in items if not it.get("x")])


if __name__ == "__main__":
    main()
